// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Resize(arg1, arg2) {
  return window['go']['main']['App']['Resize'](arg1, arg2);
}

export function RunCommand(arg1) {
  return window['go']['main']['App']['RunCommand'](arg1);
}

export function SendInput(arg1) {
  return window['go']['main']['App']['SendInput'](arg1);
}

export function StartShell() {
  return window['go']['main']['App']['StartShell']();
}
