// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// @ts-ignore
export function RunCommand(arg1) {
  // @ts-ignore
  return window['go']['main']['App']['RunCommand'](arg1);
}
