// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Resize(arg1:number,arg2:number):Promise<void>;

export function RunCommand(arg1:string):Promise<string>;

export function SendInput(arg1:string):Promise<void>;

export function StartShell():Promise<void>;
